version: 2

references:
  workspace_root: &workspace_root
    /home/circleci/project

  node_image: &node_image
    circleci/node:9.9

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  node_config: &node_config
    docker:
      - image: *node_image
    working_directory: *workspace_root

jobs:
  build:
    <<: *node_config
    steps:
      - checkout

      - run: yarn install

      - run: yarn build

      - run:
          name: prepare dist
          command: |
            rm dist/stats.json
            mv .circleci dist/.circleci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist

  deploy:
    <<: *node_config
    steps:

      - attach_workspace:
          at: .

      - run:
          name: deploy
          command: |
            git config --global user.email bot@circleci.com
            git config --global user.name circleci
            cd dist
            git init
            git add .
            git commit -m "Deploy to Github Pages"
            git push --force --quiet "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" master:gh-pages > /dev/null 2>&1


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build