name: deploy

on:
  push:
    branches:
      - master
      - feat/v3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          GMAP_API_KEY: ${{ secrets.GMAP_API_KEY }}
          TURTLEQUEUE_API_KEY: ${{ secrets.TURTLEQUEUE_API_KEY }}
          TURTLEQUEUE_USER_TOKEN: ${{ secrets.TURTLEQUEUE_USER_TOKEN }}
          PUBLIC_PATH: /geo-food/

      - uses: crazy-max/ghaction-github-pages@068e494
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GH_PAGES }}
